CREATE TABLE USUARIO( 
IDUSUARIO INTEGER NOT NULL, 
EMAIL VARCHAR2(100) NOT NULL UNIQUE, 
SENHA VARCHAR2(100) NOT NULL,  
DATANASCIMENTO DATE NOT NULL, 
RG VARCHAR2(20) NOT NULL, 
CPF VARCHAR2(20) NOT NULL, 
TELEFONE VARCHAR2(20) NOT NULL, 
ENDERECO VARCHAR2(100) NOT NULL, 
BAIRRO VARCHAR(100) NOT NULL, 
IDCIDADE INTEGER NOT NULL, 
CONSTRAINT PK_USUARIO PRIMARY KEY(IDUSUARIO), 
CONSTRAINT FK_CIDADE FOREIGN KEY(IDCIDADE) REFERENCES CIDADE(IDCIDADE));