CREATE TABLE OCORRENCIA(
IDOCORRENCIA INTEGER NOT NULL,
IDVEICULO INTEGER NOT NULL,
DATA_HORA DATE NOT NULL,
TIPO_OCORRENCIA CHAR(1) NOT NULL,
ESTACIONADO CHAR(1) NOT NULL,
ESTAVA_NO_CARRO CHAR(1) NOT NULL,
NUMERO_MELIANTES NUMBER(2) NOT NULL,
NUMERO_VITIMAS NUMBER(2) NOT NULL,
SEXO_PROPRIETARIO CHAR(1) NOT NULL,
IDADE_VITIMA NUMBER(3) NOT NULL,
MELIANTE_EM_OUTRO_VEICULO CHAR(1) NOT NULL,
OUTROS_PERTENCES_LEVADOS CHAR(1) NOT NULL,
VEICULO_SEGURADO CHAR(1) NOT NULL,
VEICULO_COM_RASTREADOR CHAR(1) NOT NULL,
SITUACAO_OCORRENCIA CHAR(1) NOT NULL,
CONSTRAINT PK_OCORRENCIA PRIMARY KEY(IDOCORRENCIA), 
CONSTRAINT FK_VEICULO FOREIGN KEY(IDVEICULO) REFERENCES VEICULO(IDVEICULO));


CREATE SEQUENCE SQ_OCORRENCIA
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;