CREATE TABLE PERMISSAO(
  ID_PERMISSAO INTEGER NOT NULL,
  PERMISSAO VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_PERMISSAO PRIMARY KEY(ID_PERMISSAO));
  
  ALTER TABLE USUARIO ADD ID_PERMISSAO INTEGER NOT NULL;
  
ALTER TABLE USUARIO ADD CONSTRAINT FK_PERMISSAO FOREIGN KEY (ID_PERMISSAO)
   REFERENCES PERMISSAO (ID_PERMISSAO);