CREATE TABLE AUDITORIA (
IDAUDITORIA INTEGER,
USUARIO VARCHAR(255),
TIPOCONSULTA VARCHAR(255),
CONSTRAINT PK_AUDITORIA PRIMARY KEY(IDAUDITORIA) );

ALTER TABLE ocorrencia add idusuario INTEGER ;
alter table OCORRENCIA add constraint IDUSUARIO_FK FOREIGN KEY(idusuario) references USUARIO(IDUSUARIO);


CREATE SEQUENCE SQ_AUDITORIA
  MINVALUE 0
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
